[app]
name = "cmdb"

[app.http]
host = "127.0.0.1"
port = "8050"

[app.grpc]
host = "127.0.0.1"
port = "18050"




[mysql]
host = "127.0.0.1"
port = "3306"
database = "go-micro"
username = "root"
password = "123456"